services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    environment:
      PYTHONPATH: /app/src
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    restart: unless-stopped
  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A regen_queue.celery_app worker --loglevel=info
    env_file:
      - .env.docker
    environment:
      PYTHONPATH: /app/src
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - redis
