version: "3.9"

services:
  app:
    build: .
    container_name: regen_app
    ports:
      - 8000:8000
    env_file:
      - .env.docker
    working_dir: /app 
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped