# Dockerfile for local development
FROM python:3.11-slim
LABEL maintainer="Rafid Mahbub" \
      version="1.1.0" \
      description="Regen Organics analytics app v1.1.0"

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY credentials.json .
COPY . .

EXPOSE 8000

CMD ["gunicorn", "-c", "gunicorn.conf.py", "flask_app:app"]
