version: "3.9"

services:
  app:
    build: .
    container_name: rmahbub503/regen_organics_analytics_app:v1
    ports:
      - 8000:8000
    env_file:
      - .env.docker
    working_dir: /app 
    command: gunicorn flask_app:app --bind 0.0.0.0:8000 --timeout 120
    restart: unless-stopped