branch-defaults:
  main:
    environment: regen-app-test
global:
  application_name: regen-organics-analytics-app
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: rafid
  repository: null
  sc: git
  workspace_type: Application
