name: AWS Credentials Debug

# Allows manual triggering
on:
  workflow_dispatch:

jobs:
  check-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1  # hardcoded for simplicity
        run: |
          echo "Partial AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:0:4}****"
          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"

          # Verify AWS CLI can see the credentials
          echo "Checking AWS identity..."
          aws sts get-caller-identity