name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ Install AWS EB CLI
      - name: Install AWS EB CLI
        run: |
          pip install --upgrade pip
          pip install awsebcli

      # 4️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 5️⃣ Debug AWS identity (optional)
      - name: Debug AWS identity
        run: aws sts get-caller-identity

      # 6️⃣ Write credentials.json from secret
      - name: Write credentials.json
        run: |
          cat <<EOF > ./credentials.json
          ${{ secrets.GEE_CREDENTIALS_JSON }}
          EOF

      # 7️⃣ Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        run: |
          # Initialize EB app
          eb init regen-organics-analytics-app --region us-east-1 --platform "Docker"
          # Deploy to environment mapped to 'main' branch in .elasticbeanstalk/config.yml
          eb deploy --staged --verbose

      # 8️⃣ Fetch EB logs if deployment fails
      - name: Fetch EB logs for debugging
        if: failure()
        continue-on-error: true
        run: |
          eb logs --all
